on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Publish package
        # Currently, only npm supports publishing packages with provenance
        # https://docs.npmjs.com/generating-provenance-statements
        # npm install --force
        # npm publish --provenance --access public
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm publish --no-git-checks
